version: '3'

services:
  otel-collector-1:
    image: otel/opentelemetry-collector-contrib:0.130.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317"        # OTLP gRPC receiver

  otel-collector-2:
    image: otel/opentelemetry-collector-contrib:0.130.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317"        # OTLP gRPC receiver

  otel-collector-3:
    image: otel/opentelemetry-collector-contrib:0.130.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317"        # OTLP gRPC receiver

  # Otel gateway (running loadbalancing exporter)
  otel-gateway:
    image: otel/opentelemetry-collector-contrib:0.130.0
    command: ["--config=/etc/otel-gateway.yaml"]
    volumes:
      - ./otel-gateway.yaml:/etc/otel-gateway.yaml
    ports:
      - 4317:4317
      - 4318:4318
    depends_on:
      - otel-collector-1
      - otel-collector-2
      - otel-collector-3

  jaeger:
    image: jaegertracing/all-in-one:1.71.0
    ports:
      - 16686:16686
