version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.71.0
    command:
      - "--collector.otlp.grpc.tls.enabled=false"
    ports:
      - "16686:16686"   # Jaeger UI
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP